### PR TITLE
Added FileIO Tests

### LINKED ISSUE #3: Add additional tests for FileIO classes
Currently the unit tests for `IsamDataObjectIO` are rather limited, this should be enhanced to cover all public methods and supported file types.

Aha! Link: https://synergex.aha.io/features/HC-121

### PR DESCRIPTION
**Pull request by theplasmastorm**
Fixes #3 

Added create test, delete test, property tests, and error checking test

### CODE REVIEW

**Comment by hippiehunter** [comment]
I'd like to see these methods tested

ReadPrevRecord
ReadRecord

Additionally I would like to see error handling tested. attempting to update when no lock is present, trying to write a duplicate key when the file wont allow it. Generally just try to cause as many of the FileAccessResults as possible.

**Comment by hippiehunter** [comment]
I just noticed the error testing, for some reason i think it wasnt showing me your full changeset when i looked at this initially. I suspect the tests that are returning FileAccessResults.UnknownError represent bugs.

**Comment by theplasmastorm** [comment]
> I'd like to see these methods tested
> 
> ReadPrevRecord
> ReadRecord
> 
> Additionally I would like to see error handling tested. attempting to update when no lock is present, trying to write a duplicate key when the file wont allow it. Generally just try to cause as many of the FileAccessResults as possible.

- Added in bbfa9f1

> I just noticed the error testing, for some reason i think it wasnt showing me your full changeset when i looked at this initially. I suspect the tests that are returning FileAccessResults.UnknownError represent bugs.

- Fixed in 3abfc41

**Comment by hippiehunter** [comment]
This looks good to me, I'll approve/merge it once the tests pass. Can you add the new error handler stuff into the docs here https://github.com/Synergex/HarmonyCore/wiki/FileIO

**Pull request merged**
